FROM apache/airflow:2.8.1

USER root
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    pyspark==3.5.0 \
    confluent-kafka==2.2.0 \
    psycopg2-binary==2.9.9 \
    python-json-logger==3.0.1 \
    boto3==1.35.69 \
    botocore==1.35.69