FROM apache/airflow:2.8.1

USER root
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/airflow/logs /opt/airflow/dags /run/secrets && \
    chown -R airflow:root /opt/airflow/logs /opt/airflow/dags /run/secrets && \
    chmod -R 775 /opt/airflow/logs /opt/airflow/dags /run/secrets

USER airflow
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt